CC = g++
CFLAGS = -Wall -g

all: reflector.o rotor.o plugboard.o

reflector.o: reflector.cpp reflector.h
	${CC} ${CFLAGS} -c reflector.cpp

rotor.o: rotor.cpp rotor.h
	${CC} ${CFLAGS} -c rotor.cpp

plugboard.o: plugboard.cpp plugboard.h
	${CC} ${CFLAGS} -c plugboard.cpp
